sintron/mainapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='index'),  # Home/Login page
    path('dashboard/', views.dashboard, name='dashboard'),  # dashboard page
    path('software/', views.software_list, name='software'),
    path('software/create/', views.software_create, name='software_create'),
    path('software/edit/<int:pk>/', views.software_edit, name='software_edit'),
    path('software/delete/<int:pk>/', views.software_delete, name='software_delete'),
    path('<str:product_extension>/download/', views.protected_redirect, name='protected_redirect'),
    path('usermanual/', views.usermanual, name='usermanual'),  # Usermanual page
    path('usermanual/create/', views.usermanual_create, name='usermanual_create'),
    path('usermanual/delete/<int:pk>/', views.usermanual_delete, name='usermanual_delete'),
    path('usermanual/pdf/<int:pk>/', views.generate_pdf, name='generate_pdf'),
    path('pdf-settings/', views.pdf_settings, name='pdf_settings'),
    path('hello/', views.hello_world, name='hello_world'),  # Hello World page
    path('', views.login_view, name='login'),  # Custom login view
    path('dashboard/', views.dashboard, name='dashboard'),  # Redirect after login
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),  # Custom logout view
]

sintron/sintron/urls.py
from django.contrib import admin
from django.urls import include, path
from mainapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('mainapp/', include('mainapp.urls')),
    path('<str:product_extension>/download/', views.protected_redirect, name='protected_redirect'),
]

sintron/mainapp/models.py
from django.db import models

class Software(models.Model):
    product_extension = models.CharField(max_length=255, unique=True)
    download_url = models.URLField(max_length=500)
    password = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.product_extension


class UserManual(models.Model):
    product_name = models.CharField(max_length=255)
    manual_url = models.URLField()

    def __str__(self):
        return self.product_name

class PDFSettings(models.Model):
    logo1 = models.ImageField(upload_to='logos/', blank=True, null=True)
    logo2 = models.ImageField(upload_to='logos/', blank=True, null=True)
    logo1_x = models.IntegerField(default=10)  # X position for logo1
    logo1_y = models.IntegerField(default=30)  # Y position for logo1
    logo2_x = models.IntegerField(default=300)  # X position for logo2
    logo2_y = models.IntegerField(default=30)  # Y position for logo2
    qr_code_x = models.IntegerField(default=280)  # X position for QR code
    qr_code_y = models.IntegerField(default=100)  # Y position for QR code
    instructions = models.TextField(blank=True, null=True)

    def __str__(self):
        return "PDF Settings"

sintron/mainapp/forms.py
from django import forms
from .models import Software, UserManual, PDFSettings

class SoftwareForm(forms.ModelForm):
    class Meta:
        model = Software
        fields = ['product_extension', 'download_url', 'password']
        widgets = {
            'product_extension': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Product Extension'}),
            'download_url': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'https://www.softwaredownloadlink.com'}),
            'password': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter URL Access Password'}),
        }

class UserManualForm(forms.ModelForm):
    class Meta:
        model = UserManual
        fields = ['product_name', 'manual_url']


class PDFSettingsForm(forms.ModelForm):
    logo1_x = forms.IntegerField(label='Logo 1 X Position')
    logo1_y = forms.IntegerField(label='Logo 1 Y Position')
    logo2_x = forms.IntegerField(label='Logo 2 X Position')
    logo2_y = forms.IntegerField(label='Logo 2 Y Position')
    qr_code_x = forms.IntegerField(label='QR Code X Position')
    qr_code_y = forms.IntegerField(label='QR Code Y Position')
    instructions = forms.CharField(widget=forms.Textarea, label='Instructions')

    class Meta:
        model = PDFSettings
        fields = ['logo1', 'logo2', 'logo1_x', 'logo1_y', 'logo2_x', 'logo2_y', 'qr_code_x', 'qr_code_y', 'instructions']

sintron/mainapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ValidationError
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO
from django.http import JsonResponse, HttpResponse, HttpResponseForbidden
from .forms import SoftwareForm, UserManualForm, PDFSettingsForm
from .models import Software, UserManual, PDFSettings
from PIL import Image
import qrcode
import tempfile
import os


def index(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    return render(request, 'mainapp/home.html')

@csrf_protect
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return HttpResponseRedirect(reverse('dashboard'))  # Redirect to the dashboard page
    else:
        form = AuthenticationForm()

    return render(request, 'mainapp/home.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('login')

@login_required
def dashboard(request):
    total_software_links = Software.objects.count()  # Count the total software links
    total_user_manual_links = UserManual.objects.count()

    context = {
        'total_software_links': total_software_links,
        'total_user_manual_links': total_user_manual_links,
    }
    return render(request, 'mainapp/dashboard.html', context)

@login_required
def software(request):
    return render(request, 'mainapp/software.html')

@login_required
def software_list(request):
    base_url = 'http://127.0.0.1:8000/'
    softwares = Software.objects.all()
    for software in softwares:
        software.full_url = f"{base_url}{software.product_extension}/download"
    return render(request, 'mainapp/software.html', {'softwares': softwares})

@login_required
def software_create(request):
    if request.method == 'POST':
        form = SoftwareForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('software')
    else:
        form = SoftwareForm()
    return render(request, 'mainapp/software.html', {'form': form})

@login_required
def software_edit(request, pk):
    software = get_object_or_404(Software, pk=pk)
    if request.method == 'POST':
        form = SoftwareForm(request.POST, instance=software)
        if form.is_valid():
            form.save()
            return redirect('software_list')  # Make sure this redirects to the software list
    else:
        form = SoftwareForm(instance=software)
    return render(request, 'mainapp/software.html', {'form': form})

@login_required
def software_delete(request, pk):
    if request.method == 'POST':
        software = get_object_or_404(Software, pk=pk)
        software.delete()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False}, status=400)

@login_required
def protected_redirect(request, product_extension):
    software = get_object_or_404(Software, product_extension=product_extension)
    if request.method == 'POST':
        password = request.POST.get('password')
        if password == software.password:
            return redirect(software.download_url)
        else:
            return HttpResponseForbidden("Incorrect password")
    return render(request, 'mainapp/password_prompt.html', {'software': software})

@login_required
def usermanual(request):
    if request.method == 'POST':
        form = UserManualForm(request.POST)
        if form.is_valid():
            instance = form.save()
            # Generate link based on product name
            product_name = instance.product_name
            generated_link = f"https://m.sintronindia.com/{product_name.replace(' ', '_').upper()}"
            instance.manual_url = generated_link
            instance.save()
            return redirect('usermanual')
    else:
        form = UserManualForm()

    manuals = UserManual.objects.all()  # Ensure you fetch all user manuals
    return render(request, 'mainapp/usermanual.html', {'form': form, 'manuals': manuals})

@login_required
def usermanual_create(request):
    if request.method == 'POST':
        form = UserManualForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('usermanual')
    else:
        form = UserManualForm()
    return render(request, 'mainapp/usermanual.html', {'form': form})

@login_required
def usermanual_delete(request, pk):
    if request.method == 'POST':
        usermanual = get_object_or_404(UserManual, pk=pk)
        usermanual.delete()
        return JsonResponse({'status': 'success'})
    return JsonResponse({'status': 'error'}, status=400)

@login_required
def pdf_settings(request):
    settings, created = PDFSettings.objects.get_or_create(pk=1)  # Use a single instance
    if request.method == 'POST':
        form = PDFSettingsForm(request.POST, request.FILES, instance=settings)
        if form.is_valid():
            form.save()
            return redirect('pdf_settings')
    else:
        form = PDFSettingsForm(instance=settings)
    return render(request, 'mainapp/pdf_settings.html', {'form': form})

@login_required
def generate_pdf(request, pk):
    usermanual = get_object_or_404(UserManual, pk=pk)
    settings = PDFSettings.objects.get(pk=1)  # Retrieve the settings

    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=(400, 200))  # Adjusted to a business card size
    width, height = 400, 200  # Width and height of the business card-like PDF

    # Top Section
    qr_size_percentage = 0.15  # Adjusted QR code size to 15% of width
    qr_width = width * qr_size_percentage

    # Instructions
    p.setFont("Helvetica", 10)
    instructions_y = height - 30
    p.drawString(10, instructions_y, "Scan QR code or go to link to Download the User Manual")

    # QR Code
    qr_code_url = f"https://m.sintronindia.com/{usermanual.product_name.replace(' ', '_').lower()}"
    qr = qrcode.QRCode(version=1, box_size=10, border=4)
    qr.add_data(qr_code_url)
    qr.make(fit=True)
    qr_img = qr.make_image(fill='black', back_color='white')

    # Use tempfile to create a temporary file for QR code
    with tempfile.NamedTemporaryFile(delete=False, suffix='.png') as temp_qr_file:
        qr_img.save(temp_qr_file)
        temp_qr_path = temp_qr_file.name

    # Draw QR Code on PDF
    qr_x_position = width - qr_width - 10
    qr_y_position = height - qr_width - 10
    p.drawImage(temp_qr_path, qr_x_position, qr_y_position, width=qr_width, height=qr_width)

    # Middle Section
    middle_section_height = 60
    p.setFillColorRGB(0.8, 0.8, 0.8)  # Grey background
    p.rect(0, height / 2 - middle_section_height / 2, width, middle_section_height, fill=1, stroke=1)
    p.setFillColorRGB(0, 0, 0)  # Black font color
    p.setFont("Helvetica", 12)
    text_width = p.stringWidth(qr_code_url, "Helvetica", 12)
    p.drawString((width - text_width) / 2, height / 2 - 10, qr_code_url)

    # Bottom Section
    bottom_section_height = 40
    logo_width = 40
    logo_height = 40

    # Calculate vertical center position for logos
    logos_center_y = 30 + (bottom_section_height - logo_height) / 2

    # Draw First Brand Logo
    if settings.logo1:
        try:
            with Image.open(settings.logo1.path) as img:
                logo_ratio = img.width / img.height
                if logo_width / logo_height > logo_ratio:
                    logo_width = logo_height * logo_ratio
                else:
                    logo_height = logo_width / logo_ratio
            p.drawImage(settings.logo1.path, 10, logos_center_y, width=logo_width, height=logo_height)
        except Exception as e:
            p.drawString(10, bottom_section_height / 2, f"Logo1 Error: {str(e)}")

    # Draw Second Brand Logo
    if settings.logo2:
        try:
            with Image.open(settings.logo2.path) as img:
                logo_ratio = img.width / img.height
                if logo_width / logo_height > logo_ratio:
                    logo_width = logo_height * logo_ratio
                else:
                    logo_height = logo_width / logo_ratio
            p.drawImage(settings.logo2.path, width - logo_width - 10, logos_center_y, width=logo_width, height=logo_height)
        except Exception as e:
            p.drawString(width - logo_width - 10, bottom_section_height / 2, f"Logo2 Error: {str(e)}")

    # Save PDF
    p.showPage()
    p.save()
    buffer.seek(0)
    # Filename based on product extension
    filename = f'{usermanual.product_name.replace(" ", "_")}.pdf'
    response = HttpResponse(buffer, content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename={filename}'

    return response

# Example of a simple view with HttpResponse
def hello_world(request):
    return HttpResponse("Hello, World!")

sintron/mainapp/templates/mainapp/footer.html
{% load static %}

<footer class="d-footer">
  <div class="row align-items-center justify-content-between">
    <div class="col-auto">
      <p class="mb-0">© 2024 Sintron India. All Rights Reserved.</p>
    </div>
    <div class="col-auto">
      <p class="mb-0">Made by <span class="text-primary-600">Manishgohel.pro</span></p>
    </div>
  </div>
</footer>

sintron/mainapp/templates/mainapp/software.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <!-- aside/sidebar Start -->
  {% include 'mainapp/sidebar.html' %}
  <!-- aside/sidebar End -->


<main class="dashboard-main">
    <!-- Dashboard Nav Start -->

    {% include 'mainapp/nav.html' %}

    <!-- Dashboard Nav End -->
    <div class="dashboard-main-body">

            <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-24">
            <h6 class="fw-semibold mb-0">Softwares</h6>
            <ul class="d-flex align-items-center gap-2">
                <li class="fw-medium">
                <a href="index.html" class="d-flex align-items-center gap-1 hover-text-primary">
                    <iconify-icon icon="solar:home-smile-angle-outline" class="icon text-lg"></iconify-icon>
                    Dashboard
                </a>
                </li>
                <li>-</li>
                <li class="fw-medium">Software</li>
            </ul>
            </div>

            <div class="card basic-data-table">
            <div class="card-header d-flex justify-content-between">
                <h5 class="card-title mb-0">Download Links</h5>
                <button type="button" class="btn rounded-pill btn-primary-600 radius-8 px-20 py-11" data-bs-toggle="modal" data-bs-target="#create-linkTaskModal">Create New Link</button>
            </div>

            <div class="card-body">
                <table class="table bordered-table mb-0" id="dataTable" data-page-length='10'>
                    <thead>
                        <tr>
                            <th scope="col">
                                <div class="form-check style-check d-flex align-items-center">
                                    <input class="form-check-input" type="checkbox">
                                    <label class="form-check-label">
                                        S.L
                                    </label>
                                </div>
                            </th>
                            <th scope="col">Name</th>
                            <th scope="col">Link</th>
                            <th scope="col">Password</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for software in softwares %}
                            <tr>
                                <td>
                                    <div class="form-check style-check d-flex align-items-center">
                                        <input class="form-check-input" type="checkbox">
                                        <label class="form-check-label">
                                            {{ forloop.counter }}
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <h6 class="text-md mb-0 fw-medium flex-grow-1">{{ software.product_extension }}</h6>
                                    </div>
                                </td>
                                <td>
                                    <a href="{{ software.full_url }}" target="_blank">{{ software.full_url }}</a>
                                </td>
                                <td>
                                    {{ software.password }}
                                </td>
                                <td>
                                    <!-- Updated Delete Button -->
                                    <button type="button" class="w-32-px h-32-px bg-danger-focus text-danger-main rounded-circle d-inline-flex align-items-center justify-content-center" onclick="confirmDelete({{ software.id }})">
                                        <iconify-icon icon="mingcute:delete-2-line"></iconify-icon>
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>
        </div>
    </div>


    <!-- Create Link Task Modal -->
    <div class="modal fade" id="create-linkTaskModal" tabindex="-1" aria-labelledby="addTaskModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h6 class="modal-title text-xl mb-0" id="addTaskModalLabel">Add Software Information</h6>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="taskForm" method="POST" action="{% url 'software_create' %}">
                        {% csrf_token %}
                        <input type="hidden" id="editTaskId" name="id" value="">

                        <div class="mb-3">
                            <label for="id_product_extension" class="form-label fw-semibold text-primary-light text-sm mb-8">Product Extension</label>
                            <input type="text" class="form-control" placeholder="Enter Product Extension" id="id_product_extension" name="product_extension" required>
                        </div>

                        <div class="mb-3">
                            <label for="id_download_url" class="form-label fw-semibold text-primary-light text-sm mb-8">Software Download URL</label>
                            <input type="url" class="form-control" placeholder="https://www.softwaredownloadlink.com" id="id_download_url" name="download_url" required>
                        </div>

                        <div class="mb-3">
                            <label for="id_password" class="form-label fw-semibold text-primary-light text-sm mb-8">Password</label>
                            <input type="text" class="form-control" placeholder="Enter URL Access Password" id="id_password" name="password" required>
                        </div>

                </div>
                <div class="modal-footer justify-content-center gap-3">
                    <button type="button" class="border border-danger-600 bg-hover-danger-200 text-danger-600 text-md px-50 py-11 radius-8" data-bs-dismiss="modal">
                        Cancel
                    </button>
                    <button type="submit" class="btn btn-primary border border-primary-600 text-md px-28 py-12 radius-8" id="saveTaskButton">
                        Save Software Link
                    </button>
                </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Delete Confirmation Modal -->
    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Delete</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this item?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger" id="confirmDeleteButton">Delete</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        function populateForm(pk) {
            fetch("{% url 'software_edit' 0 %}".replace('0', pk))
                .then(response => response.json())
                .then(data => {
                    document.getElementById('id_product_extension').value = data.product_extension;
                    document.getElementById('id_download_url').value = data.download_url;
                    document.getElementById('id_password').value = data.password;
                    document.getElementById('taskForm').action = "{% url 'software_edit' 0 %}".replace('0', pk); // Update form action URL
                    document.getElementById('editTaskId').value = pk;
                    new bootstrap.Modal(document.getElementById('create-linkTaskModal')).show();
                });
        }
    </script>

    <script>
        let deleteUrl = '';

        function confirmDelete(pk) {
            deleteUrl = "{% url 'software_delete' 0 %}".replace('0', pk); // Use 0 as a placeholder and replace with pk
            new bootstrap.Modal(document.getElementById('confirmDeleteModal')).show();
        }

        document.getElementById('confirmDeleteButton').addEventListener('click', function() {
            fetch(deleteUrl, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                }
            })
            .then(response => {
                if (response.ok) {
                    location.reload(); // Reload page to reflect the deletion
                } else {
                    alert('Failed to delete the item.');
                }
            });
        });
    </script>

  <!-- Footer Start -->
  {% include 'mainapp/footer.html' %}
  <!-- Footer End -->
</main>
{% endblock %}

sintron/mainapp/templates/mainapp/usermanual.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <!-- aside/sidebar Start -->
  {% include 'mainapp/sidebar.html' %}
  <!-- aside/sidebar End -->

<main class="dashboard-main">
    <!-- Dashboard Nav Start -->
    {% include 'mainapp/nav.html' %}
    <!-- Dashboard Nav End -->

    <div class="dashboard-main-body">

        <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-24">
        <h6 class="fw-semibold mb-0">User Manual</h6>
        <ul class="d-flex align-items-center gap-2">
            <li class="fw-medium">
            <a href="index.html" class="d-flex align-items-center gap-1 hover-text-primary">
                <iconify-icon icon="solar:home-smile-angle-outline" class="icon text-lg"></iconify-icon>
                Dashboard
            </a>
            </li>
            <li>-</li>
            <li class="fw-medium">User Manual</li>
        </ul>
        </div>

        <div class="card basic-data-table">
        <div class="card-header d-flex justify-content-between">
            <h5 class="card-title mb-0">User Manual Links</h5>
            <button type="button" class="btn rounded-pill btn-primary-600 radius-8 px-20 py-11" data-bs-toggle="modal" data-bs-target="#usermanualTaskModal">
              Add New Link
            </button>
        </div>

        <div class="card-body">
            <table class="table bordered-table mb-0" id="dataTable" data-page-length='10'>
            <thead>
                <tr>
                <th scope="col">
                    <div class="form-check style-check d-flex align-items-center">
                    <input class="form-check-input" type="checkbox">
                    <label class="form-check-label">
                        S.L
                    </label>
                    </div>
                </th>
                <th scope="col">Name</th>
                <th scope="col">Link</th>
                <th scope="col">Download PDF</th>
                <th scope="col">Action</th>
                </tr>
            </thead>
                <tbody>
                    {% for manual in manuals %}
                    <tr>
                        <td>
                            <div class="form-check style-check d-flex align-items-center">
                                <input class="form-check-input" type="checkbox">
                                <label class="form-check-label">
                                    {{ forloop.counter }}
                                </label>
                            </div>
                        </td>
                        <td>
                            <div class="d-flex align-items-center">
                                <h6 class="text-md mb-0 fw-medium flex-grow-1">{{ manual.product_name }}</h6>
                            </div>
                        </td>
                        <td>
                            <div class="d-flex align-items-center">
                                <h6 class="text-md mb-0 fw-medium flex-grow-1"><a href="{{ manual.manual_url }}" class="btn btn-primary" target="_blank">View Link</a></h6>
                            </div>
                        </td>
                        <td>
                            <a href="{% url 'generate_pdf' manual.id %}" class="btn btn-info" target="_blank">Generate PDF</a>
                        </td>
                        <td>
                            <a href="javascript:void(0)" class="w-32-px h-32-px bg-danger-focus text-danger-main rounded-circle d-inline-flex align-items-center justify-content-center" onclick="confirmDelete({{ manual.id }})">
                                <iconify-icon icon="mingcute:delete-2-line"></iconify-icon>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    </div>

    <!-- Add User Manual Modal -->
    <div class="modal fade" id="usermanualTaskModal" tabindex="-1" aria-labelledby="usermanualTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title text-xl mb-0" id="usermanualTaskModalLabel">Add User Manual Information</h6>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="usermanualForm" method="POST" action="{% url 'usermanual_create' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_product_name" class="form-label fw-semibold text-primary-light text-sm mb-8">Product Extension</label>
                        <input type="text" class="form-control" placeholder="Enter Product Extension" id="id_product_name" name="product_name" required>
                    </div>
                    <div class="mb-3">
                      <label for="manual_url" class="form-label fw-semibold text-primary-light text-sm mb-8">Manual URL</label>
                      <input type="url" class="form-control" placeholder="https://example.com/usermanual.pdf" id="id_manual_url" name="manual_url" required>
                    </div>
            </div>
            <div class="modal-footer justify-content-center gap-3">
                <button type="button" class="border border-danger-600 bg-hover-danger-200 text-danger-600 text-md px-50 py-11 radius-8" data-bs-dismiss="modal">
                    Cancel
                </button>
                <button type="submit" class="btn btn-primary border border-primary-600 text-md px-28 py-12 radius-8">
                    Save User Manual Link
                </button>
            </div>
            </form>
        </div>
    </div>
    </div>

    <!-- Delete Confirmation Modal -->
    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Delete</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this item?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger" id="confirmDeleteButton">Delete</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        let deleteUrl = '';

        function confirmDelete(pk) {
            deleteUrl = "{% url 'usermanual_delete' 0 %}".replace('0', pk);
            new bootstrap.Modal(document.getElementById('confirmDeleteModal')).show();
        }

        document.getElementById('confirmDeleteButton').addEventListener('click', function() {
            fetch(deleteUrl, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                }
            })
            .then(response => {
                if (response.ok) {
                    location.reload(); // Reload page to reflect the deletion
                } else {
                    alert('Failed to delete the item.');
                }
            });
        });
    </script>

    <!-- Footer Start -->
    {% include 'mainapp/footer.html' %}
    <!-- Footer End -->

</main>
{% endblock %}